name: Flutter Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  flutter-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wasabeef/import-asdf-tool-versions-action@v1.0.1
        id: asdf
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh ${{ steps.asdf.outputs.flutter }}
      - run: flutter pub get
      - run: flutter test