name: Flutter Analyze

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  flutter-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: 'Read flutter version from .tool-versions'
        id: flutter_info
        run: |
          flutter_info=$(grep 'flutter' .tool-versions)
          echo "::set-output name=version::$(echo ${flutter_info} | sed -r 's/^flutter ([a-z0-9\.\+\-]+)\-(stable|beta|dev)$/\1/')"
          echo "::set-output name=channel::$(echo ${flutter_info} | sed -r 's/^flutter ([a-z0-9\.\+\-]+)\-(stable|beta|dev)$/\2/')"
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh ${{ steps.flutter_info.outputs.version }}
      - run: flutter pub get
      - uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true
          annotate: true
          annotate-only: false
          working-directory: ./lib/